security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    
    providers:
        # Supprimez ou commentez la ligne des utilisateurs en mémoire
        # users_in_memory: { memory: null }
        
        # Ajoutez votre provider qui utilise l'entité User
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email # ou un autre champ unique de votre choix

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            
            # Activez le formulaire de connexion
            form_login:
                login_path: app_login
                check_path: app_login
            
            # Activez la déconnexion
            logout:
                path: app_logout
                target: app_any_route # Redirigez vers une route après la déconnexion
            custom_authenticator: App\Security\AppAuthenticator

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

    access_control:
        # Exemples d'accès contrôlés
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }